### ISSUE TITLE
Needed Chrome Build

### ISSUE THREAD

**Issue by samcarecho** [googlecodelabs/ar-with-webxr#1]
@jsantell, 

Before the API is available on Canary, where can I get the build that was available for the IO attendees?
Thanks.

**Comment by jsantell** [comment]
The build was a prerelease Chromium build for I/O only, since we can't publicly release the build -- it should be in Canary soon this week or next week however!

**Comment by samcarecho** [comment]
Thanks for the reply @jsantell.
As the ARCore team has published specific Chrome builds for developers to test, I thought that the WebXR team could do the same.

I will wait for the new Canary release.
