### ISSUE TITLE
Camera is not working properly in Canary 72

### ISSUE THREAD

**Issue by saurabh183** [googlecodelabs/ar-with-webxr#10]
Camera is not working properly after updating Canary to version 72.0.3589.0 from 70 in Pixel2 Android 9.

Portrait Mode: Screen blinks different colors after clicking the button Start Augmented Reality.

Landscape Mode: Camera detects the surrounding but displays at different angle.

Everything was working fine in Canary 70.0.3538.2  (https://youtu.be/dXODcxYQMtM).

**Comment by jsantell** [comment]
I've ran into this on a Pixel 1, but then worked after trying again. Maybe an intermittent issue?

**Comment by jsantell** [comment]
Filed: https://bugs.chromium.org/p/chromium/issues/detail?id=898978

**Comment by jsantell** [comment]
A fix has landed for this and should be in an upcoming Canary.
