### ISSUE TITLE
Wrong link to WebXR Device API on blog

### ISSUE THREAD

**Issue by keemor** [googlecodelabs/ar-with-webxr#19]
On https://codelabs.developers.google.com/codelabs/ar-with-webxr/#0 
the link to **WebXR Device API** should be 
https://immersive-web.github.io/webxr/ 
instead of 
https://immersive-web.github.io/webxr/spec/latest/ which is 404

**Comment by jsantell** [comment]
Thanks for filing an issue! The codelab has now been updated with the latest link
