### ISSUE TITLE
Not working on Samsung S7 on local server and total lagging on published demo

### ISSUE THREAD

**Issue by esnho** [googlecodelabs/ar-with-webxr#5]
Hello,
After I saw the demo at https://web-education-ar-demo.appspot.com/ . Very cool and smooth.

I started digging around the browser-AR  tech and found this repository and looks like a good starting point for me.

I followed the tutorial at https://codelabs.developers.google.com/codelabs/ar-with-webxr/#0 and I successfully served your app via the Web Server Chrome extension but if I visit the page using my smartphone it says that the browser is not supported.

If I visit your demo at https://googlecodelabs.github.io/ar-with-webxr/final/ it works. It lag a lot but at least it works.

From Canary I get these info:
App version: **69.0.3469.0**
OS version: **Android 8.0.0, SM-G930F Build/R16NW**

Working demo screenshot: https://photos.app.goo.gl/PUnAkHRipBr9jUfb7

Not Working demo screenshot: https://photos.app.goo.gl/RNe9hbXZPzGEnnBE7

**Comment by esnho** [comment]
Post Scrittum:

After a little debugging I found that on the local network server the navigator does not contains xr. See screenshot in the link

https://photos.app.goo.gl/fBxTUeNpuQFWrfWN6

**Comment by jsantell** [comment]
I think you're running into the same issue as #4 -- the WebXR requires a secure context and is only available on HTTPS or localhost

**Comment by esnho** [comment]
@jsantell you are right. I've created a self signed certificate and used http-server-ssl (npm) to serve the page and it worked.
Unfortunately the demo is very laggy even after replacing the fox with a simple cube, I will investigate
